### ISSUE TITLE
Prerenderer 

### ISSUE THREAD

**Issue by bwind** [kgierke/nuxt-basic-auth#2]
First of all, thanks for the great work on this module. I'm bumping into an issue with building my Nuxt app for production. If basicAuth is enabled, prerendering won't work as the crawler will hit `401 Unauthorized` responses. Is there a way we can either disable auth for the prerender part, or configure prerenderer to use the basic auth credentials while crawling?

**Comment by kgierke** [comment]
Hi, thats a good question, I haven't used the pretender function so far, so I'll have a look into it as soon as I got some spare time. I will update this issue accordingly

**Comment by kgierke** [comment]
Implemented a fix and published it under `1.4.0`
