### ISSUE TITLE
Typescript support ?

### ISSUE THREAD

**Issue by MathieuDerelle** [kgierke/nuxt-basic-auth#6]
I'm getting the error

```
Object literal may only specify known properties, and 'basicAuth' does not exist in type 'InputConfig<NuxtConfig, ConfigLayerMeta>'.ts(2353)
```

when following 
https://github.com/kgierke/nuxt-basic-auth?tab=readme-ov-file#quick-setup

**Comment by MathieuDerelle** [comment]
hmmm, im not sure what happened but I dont have the error anymore...

**Comment by kgierke** [comment]
Can happen sometimes if Nuxt isn't initialised fully. Glad it works now.
