### ISSUE TITLE
Some letters not allowed in password

### ISSUE THREAD

**Issue by rotsee** [kgierke/nuxt-basic-auth#8]
This wook a while to figure out, but it seems like this module will refuse to authenticate users that have some common latin letters in the password, e.g. `å`, `ö`, `ñ` or `ı`, and it will also fail for any(?) non latin character (e.g. `暗号`). Could it be that only ascii characters work, for some reason?

**Comment by kgierke** [comment]
Very good catch, that was caused due to encoding the authentication header by default as `ascii`. I changed the encoding to `utf-8` in 7d778cf

**Comment by kgierke** [comment]
Released with: [1.6.0](https://github.com/kgierke/nuxt-basic-auth/releases/tag/v1.6.0)

**Comment by rotsee** [comment]
Wonderful, thank you!
